#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
firstNum=1
secondNum=1
sum=0
UserInput=int(input("Plese Enter a Number..."))
print(firstNum)
print(secondNum)
for i in range(1,UserInput):
    temp=firstNum+secondNum
    if temp>=4000000:break
    if temp%2==0:
        sum+=temp
    firstNum=secondNum
    secondNum=temp
    print(temp)
print("Sum of all the even fab numbers is:",sum)
